### ISSUE TITLE
Non-empty string assertion

### ISSUE THREAD

**Issue by thiemowmde** [wikimedia/Assert#17]
I see this pattern very, very often in our code base and would love to have a short assertion for this:
```php
if ( !is_string( $var ) || $var === '' ) {
    throw new InvalidArgumentException( '$var must be a non-empty string' );
}
```

**Comment by mariushoch** [comment]
This could be either `Assert::nonEmptyString( $value, $name )` or a new "magic" type like `Assert::parameterType( 'nonEmtpyString', $value, $name )`. Out of these options, I clearly prefer the first one.

**Comment by thiemowmde** [comment]
Resubmitted as https://gerrit.wikimedia.org/r/316324.
